// Code generated by 'ant gen' command.
// DO NOT EDIT!

package model

import (
	"database/sql"
	"time"

	"github.com/henrylee2cn/goutil/coarsetime"
	tp "github.com/henrylee2cn/teleport"
	"github.com/xiaoenai/ants/model"
	"github.com/xiaoenai/ants/model/sqlx"
)

// DivideArg divide api arg
type DivideArg struct {
	Id int64 `json:"id"`
	// dividend
	A float64 `json:"a"`
	// divisor
	B         float64 `json:"b" param:"<range: 0.01:100000>"`
	CreatedAt int64   `json:"created_at"`
	UpdatedAt int64   `json:"updated_at"`
}

// TableName implements 'github.com/xiaoenai/ants/model'.Cacheable
func (*DivideArg) TableName() string {
	return "divide_arg"
}

var divideArgDB, _ = dbHandler.RegCacheableDB(new(DivideArg), time.Hour*24, ``)

// GetDivideArgDB returns the DivideArg DB handler.
func GetDivideArgDB() *model.CacheableDB {
	return divideArgDB
}

// InsertDivideArg insert a DivideArg data into database.
func InsertDivideArg(_d *DivideArg, tx ...*sqlx.Tx) (int64, error) {
	_d.UpdatedAt = coarsetime.FloorTimeNow().Unix()
	if _d.CreatedAt == 0 {
		_d.CreatedAt = _d.UpdatedAt
	}
	return _d.Id, divideArgDB.Callback(func(tx model.DbOrTx) error {
		var query string
		if _d.Id > 0 {
			query = "INSERT INTO `divide_arg` (id,`a`,`b`,`created_at`,`updated_at`)VALUES(:id,:a,:b,:created_at,:updated_at);"
		} else {
			query = "INSERT INTO `divide_arg` (`a`,`b`,`created_at`,`updated_at`)VALUES(:a,:b,:created_at,:updated_at);"
		}
		r, err := tx.NamedExec(query, _d)
		if err != nil {
			return err
		}
		id, err := r.LastInsertId()
		if err != nil {
			return err
		}
		_d.Id = id
		err = divideArgDB.PutCache(_d)
		if err != nil {
			tp.Errorf("%s", err.Error())
		}
		return nil
	}, tx...)
}

// UpdateDivideArgByPrimary update the DivideArg data in database by primary key.
// NOTE:
//  _updateFields' members must be snake format;
//  Automatic update updated_at field;
//  Don't update the primary key and the created_at key;
//  Update all fields except the primary key and the created_at key if _updateFields is empty.
func UpdateDivideArgByPrimary(_d *DivideArg, _updateFields []string, tx ...*sqlx.Tx) error {
	return divideArgDB.Callback(func(tx model.DbOrTx) error {
		_d.UpdatedAt = coarsetime.FloorTimeNow().Unix()
		var err error
		if len(_updateFields) == 0 {
			_, err = tx.NamedExec("UPDATE `divide_arg` SET `a`=:a,`b`=:b,`updated_at`=:updated_at WHERE id=:id LIMIT 1;", _d)
		} else {
			var query = "UPDATE `divide_arg` SET "
			for _, s := range _updateFields {
				if s == "updated_at" || s == "id" || s == "created_at" {
					continue
				}
				query += "`" + s + "`=:" + s + ","
			}
			if query[len(query)-1] != ',' {
				return nil
			}
			query += "`updated_at`=:updated_at WHERE id=:id LIMIT 1;"
			_, err = tx.NamedExec(query, _d)
		}
		if err != nil {
			return err
		}
		err = divideArgDB.PutCache(_d)
		if err != nil {
			tp.Errorf("%s", err.Error())
		}
		return nil
	}, tx...)
}

// DeleteDivideArgByPrimary delete a DivideArg data in database by primary key.
func DeleteDivideArgByPrimary(id int64, tx ...*sqlx.Tx) error {
	return divideArgDB.Callback(func(tx model.DbOrTx) error {
		_, err := tx.Exec("DELETE FROM `divide_arg` WHERE id=?;", id)
		if err != nil {
			return err
		}
		err = divideArgDB.PutCache(&DivideArg{
			Id: id,
		})
		if err != nil {
			tp.Errorf("%s", err.Error())
		}
		return nil
	}, tx...)
}

// GetDivideArgByPrimary query a DivideArg data from database by primary key.
// If @return bool=false error=nil, means the data is not exist.
func GetDivideArgByPrimary(id int64) (*DivideArg, bool, error) {
	var _d = &DivideArg{
		Id: id,
	}
	err := divideArgDB.CacheGet(_d)
	switch err {
	case nil:
		if _d.CreatedAt == 0 {
			return nil, false, nil
		}
		return _d, true, nil
	case sql.ErrNoRows:
		err2 := divideArgDB.PutCache(_d)
		if err2 != nil {
			tp.Errorf("%s", err2.Error())
		}
		return nil, false, nil
	default:
		return nil, false, err
	}
}

// GetDivideArgByWhere query a DivideArg data from database by WHERE condition.
// If @return bool=false error=nil, means the data is not exist.
func GetDivideArgByWhere(whereCond string, arg ...interface{}) (*DivideArg, bool, error) {
	var _d = new(DivideArg)
	err := divideArgDB.Get(_d, "SELECT id,`a`,`b`,`created_at`,`updated_at` FROM `divide_arg` WHERE "+whereCond+" LIMIT 1;", arg...)
	switch err {
	case nil:
		return _d, true, nil
	case sql.ErrNoRows:
		return nil, false, nil
	default:
		return nil, false, err
	}
}

// SelectDivideArgByWhere query some DivideArg data from database by WHERE condition.
func SelectDivideArgByWhere(whereCond string, arg ...interface{}) ([]*DivideArg, error) {
	var objs = new([]*DivideArg)
	err := divideArgDB.Select(objs, "SELECT id,`a`,`b`,`created_at`,`updated_at` FROM `divide_arg` WHERE "+whereCond, arg...)
	return *objs, err
}

// CountDivideArgByWhere count DivideArg data number from database by WHERE condition.
func CountDivideArgByWhere(whereCond string, arg ...interface{}) (int64, error) {
	var count int64
	err := divideArgDB.Get(&count, "SELECT count(1) FROM `divide_arg` WHERE "+whereCond, arg...)
	return count, err
}
