// Code generated by 'ant gen' command.
// DO NOT EDIT!

package api

import (
	tp "github.com/henrylee2cn/teleport"
	"github.com/henrylee2cn/tp-micro/examples/template/logic"
	"github.com/henrylee2cn/tp-micro/examples/template/types"
)

// Home comment...
func Home(ctx tp.PullCtx, args *struct{}) (*types.HomeReply, *tp.Rerror) {
	return logic.Home(ctx, args)
}

// Math controller
type Math struct {
	tp.PullCtx
}

// Divide handler
func (m *Math) Divide(args *types.DivideArgs) (*types.DivideReply, *tp.Rerror) {
	return logic.Math_Divide(m.PullCtx, args)
}

// Stat comment...
func Stat(ctx tp.PushCtx, args *types.StatArgs) *tp.Rerror {
	return logic.Stat(ctx, args)
}
