// Code generated by 'ant gen' command.
// DO NOT EDIT!

package sdk

import (
	"testing"

	tp "github.com/henrylee2cn/teleport"
	micro "github.com/henrylee2cn/tp-micro"
	"github.com/henrylee2cn/tp-micro/discovery/etcd"

	"github.com/henrylee2cn/tp-micro/template/types"
)

// TestSdk test SDK.
func TestSdk(t *testing.T) {
	Init(
		micro.CliConfig{
			Failover:        3,
			HeartbeatSecond: 4,
		},
		etcd.EasyConfig{
			Endpoints: []string{"http://127.0.0.1:2379"},
		},
	)

	{
		reply, rerr := Home(new(struct{}))
		if rerr != nil {
			tp.Errorf("Home: rerr: %v", rerr)
		} else {
			tp.Infof("Home: reply: %#v", reply)
		}
	}
	{
		reply, rerr := Math_Divide(new(types.DivideArgs))
		if rerr != nil {
			tp.Errorf("Math_Divide: rerr: %v", rerr)
		} else {
			tp.Infof("Math_Divide: reply: %#v", reply)
		}
	}
	{
		rerr := Stat(new(types.StatArgs))
		tp.Infof("Stat: rerr: %v", rerr)
	}
}
