// Code generated by 'ant gen' command.
// DO NOT EDIT!

package sdk

import (
	"testing"

	tp "github.com/henrylee2cn/teleport"
	micro "github.com/henrylee2cn/tp-micro"
	"github.com/henrylee2cn/tp-micro/examples/template/types"
)

// TestSdk test SDK.
func TestSdk(t *testing.T) {
	Init(
		micro.CliConfig{
			Failover:        3,
			HeartbeatSecond: 4,
		},
		micro.NewStaticLinker(":9090"),
	)

	{
		reply, rerr := Home(&struct{}{})
		if rerr != nil {
			tp.Errorf("Home: rerr: %v", rerr)
		} else {
			tp.Infof("Home: reply: %#v", reply)
		}
	}
	{
		reply, rerr := Math_Divide(&types.DivideArgs{})
		if rerr != nil {
			tp.Errorf("Math_Divide: rerr: %v", rerr)
		} else {
			tp.Infof("Math_Divide: reply: %#v", reply)
		}
	}
	{
		rerr := Stat(&types.StatArgs{})
		tp.Infof("Stat: rerr: %v", rerr)
	}
}
