// Code generated by 'ant gen' command.
// DO NOT EDIT!

package sdk

import (
	tp "github.com/henrylee2cn/teleport"
	"github.com/henrylee2cn/teleport/socket"
	micro "github.com/henrylee2cn/tp-micro"
	"github.com/henrylee2cn/tp-micro/examples/template/types"
)

var client *micro.Client

// Init init client with config and linker.
func Init(cliConfig micro.CliConfig, linker micro.Linker) {
	client = micro.NewClient(
		cliConfig,
		linker,
	)
}

// InitWithClient init client with current client.
func InitWithClient(cli *micro.Client) {
	client = cli
}

// Home comment...
func Home(args *struct{}, setting ...socket.PacketSetting) (*types.HomeReply, *tp.Rerror) {
	reply := new(types.HomeReply)
	rerr := client.Pull("/template/home", args, reply, setting...).Rerror()
	return reply, rerr
}

// Math_Divide handler
func Math_Divide(args *types.DivideArgs, setting ...socket.PacketSetting) (*types.DivideReply, *tp.Rerror) {
	reply := new(types.DivideReply)
	rerr := client.Pull("/template/math/divide", args, reply, setting...).Rerror()
	return reply, rerr
}

// Stat comment...
func Stat(args *types.StatArgs, setting ...socket.PacketSetting) *tp.Rerror {
	return client.Push("/template/stat", args, setting...)
}
