sample:
  srv:
    tls_cert_file: ""
    tls_key_file: ""
    default_session_age: 0s
    default_context_age: 0s
    slow_comet_duration: 0s
    default_body_codec: ""
    print_detail: false
    count_time: false
    network: ""
    listen_address: :9090
    enable_heartbeat: true
  etcd:
    endpoints:
    - http://127.0.0.1:2379
    dial_timeout: 0s
    username: ""
    password: ""
  db:
    database: ""
    username: ""
    password: ""
    host: ""
    port: 3306
    max_idle_conns: 0
    max_open_conns: 0
    conn_max_lifetime: 0
    no_cache: false
  redis:
    deploy_type: single
    for_single:
      addr: 127.0.0.1:6379
    for_cluster:
      addrs: []
    pool_size_per_node: 0
    idle_timeout: 0
  log_level: TRACE
