micro_cli:
  network: tcp
  local_ip: 0.0.0.0
  tls_cert_file: ""
  tls_key_file: ""
  default_session_age: 0s
  default_context_age: 0s
  default_dial_timeout: 0s
  redial_times: 0
  failover: 0
  slow_comet_duration: 0s
  default_body_codec: ""
  print_detail: false
  count_time: false
  heartbeat_second: 0
  sess_max_quota: 100
  sess_max_idle_duration: 3m0s
  circuit_breaker:
    enable: false
    error_percentage: 50
    break_duration: 5s

micro_srv:
  count_time: false
  default_body_codec: ""
  default_context_age: 0s
  default_session_age: 0s
  enable_heartbeat: false
  listen_address: 0.0.0.0:9090
  network: tcp
  print_detail: false
  slow_comet_duration: 0s
  tls_cert_file: ""
  tls_key_file: ""
