// Code generated by 'ant gen' command.
// DO NOT EDIT!

package types

// HomeReply home reply
type HomeReply struct {
	Content string `json:"content"` // text
}

type (
	// DivideArgs divide api args
	DivideArgs struct {
		// dividend
		A float64 `json:"a"`
		// divisor
		B float64 `json:"b" param:"<range: 0.01:100000>"`
	}

	// DivideReply divide api result
	DivideReply struct {
		// quotient
		C float64 `json:"c"`
	}
)

// StatArgs stat handler args
type StatArgs struct {
	Ts int64 `json:"ts"` // timestamps
}
